# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: vzotov-releases # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_REPO_USERNAME
          server-password: MAVEN_REPO_PASSWORD
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          MAVEN_REPO_USERNAME: github-publisher
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
